FROM node:16-alpine

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./

RUN npm install

COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]

#docker build -f Dockerfile.dev -t allisone4/react .
#docker run -it -p 3000:3000 -v home/node/app/node_modules -v ~/frontend:/home/node/app  allisone4/react